const packages=[["R180",20],["R500",50],["R1,800",180],["R3,500",350],["R5,000",500],["R8,000",800],["R10,000",1000],["R20,000",2000]];
function go(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");scrollTo({top:0,behavior:"smooth"})}
packageList.innerHTML=packages.map((p,i)=>`<button class="pkg" onclick="selectPackage(${i})"><span><b>${p[0]}</b><small>Configured package</small></span><span class="reward">R${p[1]} / DAY</span></button>`).join("");
function register(){let p=regPhone.value.trim(),a=regPin1.value,b=regPin2.value;if(!p||!/^[0-9]{4}$/.test(a)||a!==b)return alert("Enter a cellphone number and matching 4-digit PIN.");alert("Demo account created. A secure backend would generate the unique letters-only client code.");go("login")}
function login(){if(!loginPhone.value.trim()||!/^[0-9]{4}$/.test(loginPin.value))return alert("Enter your cellphone number and 4-digit PIN.");go("dashboard")}
function selectPackage(i){activePackage.textContent=packages[i][0]+" PACKAGE";alert("Demo package selected. No funds were moved.");go("dashboard")}
function activateReward(b){b.disabled=true;b.textContent="ACTIVATED";rewardText.textContent="TODAY'S REWARD ACTIVATED";alert("Demo activation recorded — no funds were created.")}
function saveBank(){if(!bankName.value.trim()||!accountNumber.value.trim())return alert("Enter bank name and account number.");alert("Demo bank details saved.")}
function method(m){bankBtn.classList.toggle("active",m==="bank");usdtBtn.classList.toggle("active",m==="usdt");bankForm.classList.toggle("hidden",m!=="bank");usdtForm.classList.toggle("hidden",m!=="usdt")}
function withdraw(m){let a=(m==="bank"?bankAmount:usdtAmount).value.trim();if(!a)return alert("Enter an amount.");if(m==="usdt"&&!usdtAddress.value.trim())return alert("Enter the USDT wallet address.");alert("Demo withdrawal request created — no funds or cryptocurrency were moved.")}
function adminLogin(){if(prompt("Prototype admin access code:")==="GROWX-ADMIN")go("admin");else alert("Access denied.")}
const requests=[["KTRXWQ","R1,000.00","2026-08-08 09:14","BANK"],["LMNQZA","R750.00","2026-08-09 11:32","USDT"],["ABCDXY","R2,500.00","2026-08-10 08:47","BANK"],["QWERTY","R500.00","2026-08-11 10:05","USDT"]];
queue.innerHTML=requests.map((r,i)=>`<div class="request"><div class="requesttop"><b>#${i+1} · ${r[0]}</b><span>● PENDING</span></div><div class="requestamount">${r[1]}</div><div class="requestmeta"><span>${r[3]}</span><span>${r[2]}</span></div></div>`).join("");
function openClient(){let q=search.value.trim().toUpperCase();if(!q)return alert("Enter a cellphone number or client code.");clientPanel.innerHTML=`<div class="row"><span>CLIENT CODE</span><b>${q.match(/^[A-Z]+$/)?q:"KTRXWQ"}</b></div><div class="row"><span>CELLPHONE</span><b>••••••1234</b></div><div class="row"><span>PACKAGE</span><b>R5,000</b></div><div class="row"><span>BALANCE</span><b>R8,450.00</b></div><div class="row"><span>BANK</span><b>Configured</b></div><div class="row"><span>ACCOUNT</span><b>••••1234</b></div><label>AUTHORISED ALLOCATION</label><input id="alloc" inputmode="decimal" placeholder="0.00"><label>TRANSACTION REFERENCE</label><input id="ref" placeholder="Reference"><button class="primary" onclick="allocate()">RECORD DEMO ALLOCATION</button>`}
function allocate(){if(!alloc.value.trim()||!ref.value.trim())return alert("Enter amount and transaction reference.");alert("Demo allocation recorded. No real funds were created or moved.")}